stages:
  - name: Build & Publish
    when:
      branch: cloud
      event: [push, pull request]
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: cloud-bot:${CICD_EXECUTION_SEQUENCE}
        env:
          PLUGIN_MTU: 1450
  - name: Deploy
    when:
      branch: cloud
      event: [push, pull request]
    steps:
      - applyYamlConfig:
          path: ./cloud_bot/bot-dc.yaml
