stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cloud-bot:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: 1450
  when:
    event:
      include:
      - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./bot-dc.yaml
  when:
    event:
      include:
      - tag
timeout: 60
notification: {}